export enum GitlabPipeline {
  STACK_NAME,
  ENVIRONMENT,
  GIT_TAG,
  RESOURCE,
  RESOURCE_SUBTYPE,
  COST_CENTER_TAG,
  DELETE_S3_STATIC_IPs,
  NEW_SPLITTER_DEPLOYED,
  SPLITTER_STACK_NAME,
  HOLD_REMOVAL_SERVICE_ROUTE53,
  PROXY_ROUTE53,
  SN_SHORT_DESCRIPTION,
  SN_DESCRIPTION,
  INSTANCE,
  IS_PRODUCTION
}
